version: '2'
services:
  mysql:
    image: mysql:5.5
    container_name: spam_database
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: SPAM
      MYSQL_USER: mmuster
      MYSQL_PASSWORD: studyplanning
  php:
    build: ./docker/apache
    container_name: spam_php
    links:
      - mysql:db
    volumes:
      - .:/var/www/html/~SPAM/
    environment:
      DB_HOST: db
      DB_NAME: SPAM
      DB_USER: mmuster
      DB_PASSWORD: studyplanning
      DEV: 1
      DEBUG: 1
      LOCAL: 1
    ports:
      - 8080:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: spam_phpmyadmin
    links:
      - mysql:db
    environment:
      PMA_USER: mmuster
      PMA_PASSWORD: studyplanning
    ports:
      - 8081:80
