FROM php:5.6-apache
RUN docker-php-source extract \
  && apt-get -qq update \
  && apt-get -qq install libmcrypt-dev libldap2-dev nano -y \
  && rm -rf /var/lib/apt/lists/* \
  && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu \
  && docker-php-ext-install ldap pdo pdo_mysql \
  && a2enmod rewrite \
  && a2enmod ssl \
  && docker-php-source delete
